#! /bin/bash

mlt() {
	echo 'Michael Trigoboff'
}
chw() {
	echo 'Chow'
}

ltc() {
        echo 'Liam Crawshaw'
}

ray() {
		echo 'Raymond Aguilera'
}

run() {  ltc
         mlt
	     chw
		 ray
 }

 run


